### PR TITLE
Use new module imports

### PR DESCRIPTION
**Pull request by Turbo87**
similar to https://github.com/kellyselden/ember-awesome-macros/pull/358

see https://github.com/ember-cli/ember-rfc176-data

### CODE REVIEW

**Comment by kellyselden** [comment]
@Turbo87 should I merge now or wait for defineProperty to be fixed?

**Comment by Turbo87** [comment]
I think you can merge now. The important part here is no longer using the `ember-cli-shims` so that we can avoid the deprecation messages.

**Comment by kellyselden** [comment]
Can `ember-cli-shims' be removed as a dev dep after this?

**Comment by Turbo87** [comment]
not yet, but hopefully soon

**Pull request merged**
